version: '3'

services:
  introducer:
    container_name: introducer
    environment:
      - INTRODUCER=1
    build: .

  worker:
    depends_on:
      - "introducer"
    build: .

  # pizza:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # wasabipeas:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # calzone:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # lajiao:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # mala:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # spicypeanuts:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # chocolatealmonds:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # lemontart:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # hempmilk:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # fork:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # spoon:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # knife:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # butter:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # butterbutter:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # yerbamate:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # fish:
  #   depends_on:
  #     - "introducer"
  #   build: .

  # fishsticks:
  #   depends_on:
  #     - "introducer"
  #   build: .
