version: '3'

# Fuck.
services:
  introducer:
    container_name: introducer
    environment:
      - INTRODUCER=1
    ports:
      - "6000:6000"
      - "6001:6001"
    build: .

  # Would like to use ./wait-for-it.sh but have no idea how to get containers to be able to curl each other
  pizza:
    depends_on:
      - "introducer"
    build: .

  # pepperoni:
  #   depends_on:
  #     - "introducer"
  #   build: .
